# Generated by Django 3.2.21 on 2023-10-09 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='carousel_review',
        ),
    ]
