# Generated by Django 3.2.21 on 2023-10-09 12:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_remove_product_has_sizes"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Product_status",
            new_name="ProductStatus",
        ),
    ]
